// Fix-plan emission for patches that exceed the safe-auto-apply bounds.
//
// PRD FR-FIX-1: a generated patch must touch ≤ 3 files and change ≤ 100 LoC.
// FR-FIX-3: when those bounds are exceeded, emit a "fix plan" — a numbered
// set of steps with file/line anchors — instead of an applyable patch.
//
// This module:
//   - countPatchBounds(patch) → { files, loc, exceedsBounds }
//   - renderFixPlan(finding, opts) → markdown string
//   - emitFixPlanFile(scanRoot, finding, opts) → path to .agentic-security/fix-plans/<stableId>.md

import * as fs from 'node:fs';
import * as path from 'node:path';

const MAX_FILES = 3;
const MAX_LOC   = 100;

// `patch` is a map { [file]: newContent } OR a unified-diff style string.
// We accept the map form (what fix-verify uses) and the {file, replacement}
// form (what apply_fix uses).
export function countPatchBounds(patch, originalContents = {}) {
  if (!patch) return { files: 0, loc: 0, exceedsBounds: false };
  // Case 1: { [file]: newContent } map.
  if (typeof patch === 'object' && !patch.replacement && !patch.code) {
    const files = Object.keys(patch);
    let loc = 0;
    for (const f of files) {
      const orig = originalContents[f] || '';
      const nv = patch[f] || '';
      loc += Math.abs(nv.split('\n').length - orig.split('\n').length);
    }
    return { files: files.length, loc, exceedsBounds: files.length > MAX_FILES || loc > MAX_LOC };
  }
  // Case 2: { file, replacement } single-file shape.
  if (patch.replacement && patch.file) {
    const orig = originalContents[patch.file] || '';
    const loc = Math.abs(patch.replacement.split('\n').length - orig.split('\n').length);
    return { files: 1, loc, exceedsBounds: loc > MAX_LOC };
  }
  return { files: 0, loc: 0, exceedsBounds: false };
}

// Render a markdown fix plan for a finding. The plan emits anchored steps
// the engineer (or another Claude Code turn) can follow to implement the
// architectural change manually.
export function renderFixPlan(finding, opts = {}) {
  const { reason = 'patch-exceeds-bounds', bounds = null } = opts;
  const head = `# Fix plan: ${finding.vuln || 'finding'}\n\n`;
  const meta = [
    `**Stable ID:**  \`${finding.stableId || '(none)'}\``,
    `**Severity:**   ${finding.severity || '?'}`,
    `**CWE:**        ${finding.cwe || '(unmapped)'}`,
    `**File:**       \`${finding.file || '?'}:${finding.line || '?'}\``,
    `**Confidence:** ${finding.confidence ?? '?'}`,
    `**Reason:**     ${reason}${bounds ? ` (touches ${bounds.files} files, Δ ${bounds.loc} LoC)` : ''}`,
  ].join('  \n') + '\n\n';

  const why = `## What this finding is\n\n${finding.description || finding.snippet || '(no description)'}\n\n`;

  const remediation = typeof finding.remediation === 'string'
    ? finding.remediation
    : (finding.fix?.description || '(no remediation text on the finding)');

  // Anchored steps — for non-architectural findings, this is a 3-step skeleton.
  // The caller can elaborate by passing opts.steps[].
  const steps = Array.isArray(opts.steps) && opts.steps.length ? opts.steps : [
    {
      title: `Locate the affected code`,
      anchor: `${finding.file || '?'}:${finding.line || '?'}`,
      detail: 'Open the file at the cited line and read ±10 lines of surrounding code so you understand the data flow.',
    },
    {
      title: `Apply the per-rule remediation`,
      anchor: null,
      detail: remediation,
    },
    {
      title: `Re-scan to confirm the finding is gone`,
      anchor: null,
      detail: 'Run `/scan` then check that the finding with the stable ID above is no longer present. If it persists, the patch did not address the root cause.',
    },
    {
      title: `Run the project linter on the touched files`,
      anchor: null,
      detail: 'eslint / ruff / golangci-lint / checkstyle as appropriate. The auto-fixer also runs this gate before applying.',
    },
  ];

  let body = '## Steps\n\n';
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    body += `${i + 1}. **${s.title}**`;
    if (s.anchor) body += `  \n   _Anchor:_ \`${s.anchor}\``;
    if (s.detail) body += `  \n   ${s.detail.split('\n').join('\n   ')}`;
    body += '\n\n';
  }

  const footer = `---\n_Generated by agentic-security. After implementing the steps, run \`/scan\` and (when clean) commit. To clear this plan, delete this file._\n`;
  return head + meta + why + body + footer;
}

// Write a fix-plan markdown file to .agentic-security/fix-plans/.
// Returns the absolute path of the written file, or null on error.
export function emitFixPlanFile(scanRoot, finding, opts = {}) {
  if (!scanRoot || !finding) return null;
  const dir = path.join(scanRoot, '.agentic-security', 'fix-plans');
  try { fs.mkdirSync(dir, { recursive: true }); } catch { return null; }
  const id = finding.stableId || finding.id || `unknown-${Date.now().toString(36)}`;
  const fp = path.join(dir, `${id}.md`);
  try {
    fs.writeFileSync(fp, renderFixPlan(finding, opts));
    return fp;
  } catch { return null; }
}

// Decide whether a finding warrants a fix-plan instead of an applyable patch.
// Used by /fix-style flows. Returns the bounds so the caller can decide.
export function shouldEmitFixPlan(finding, patch, originalContents) {
  const bounds = countPatchBounds(patch, originalContents);
  return { ...bounds, recommendsFixPlan: bounds.exceedsBounds };
}
