#!/usr/bin/env python3
"""
run-poc-tests.py — batch-execute PoC test files generated by
                   /agentic-security:validate-findings

Beyond running canonical PoCs, this script offers six red-team-grade modes:

  --variants       Run all adversarial variants of each PoC (WAF/filter bypass surface)
  --auth-ladder    Run each PoC under unauth / low-priv / high-priv contexts
  --verify-fix     After /fix has been applied, confirm the PoC no longer fires
  --chains         Correlate TP_PROVEN findings into multi-step attack chains
  --blind          Spin up a local OOB callback listener for blind SQLi/SSRF/XSS
  --post-exploit   Show post-exploitation suggestions for each TP_PROVEN finding

Flags can be combined. Defaults match prior behaviour (canonical PoC only).
Stdlib only — no third-party dependencies.

Project state used:
  .agentic-security/last-scan.json            scanner output
  .agentic-security/poc/<id>/poc.<ext>        generated PoC test file
  .agentic-security/poc/<id>/variants.json    optional, for --variants
  .agentic-security/auth-fixtures.json        optional, for --auth-ladder
  .agentic-security/poc-cache/                verdict cache
"""

from __future__ import annotations

import argparse
import hashlib
import http.server
import json
import os
import socket
import subprocess
import sys
import threading
import time
import uuid
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

# ─────────────────────────────────────────────────────────────────────────────
# 1. Constants
# ─────────────────────────────────────────────────────────────────────────────

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
SCRIPT_DIR = Path(__file__).resolve().parent

FRAMEWORK_RUNNERS = {
    "jest":        ["npx", "jest", "--"],
    "vitest":      ["npx", "vitest", "run"],
    "mocha":       ["npx", "mocha"],
    "node-test":   ["node", "--test"],
    "pytest":      ["pytest", "-v"],
    "rspec":       ["bundle", "exec", "rspec"],
    "phpunit":     ["./vendor/bin/phpunit"],
}

VERDICT_ICONS = {
    "TP_PROVEN":                   "FAIL ",
    "PROBABLE_FP_VERIFIED":        "PASS ",
    "INDETERMINATE_TEST_INVALID":  "ERR  ",
    "CACHED":                      "CACHE",
    "NO_POC":                      "----- ",
    "SKIPPED":                     "SKIP ",
    "FIX_VERIFIED":                "FIXED",
    "FIX_INCOMPLETE":              "BROKE",
    "TP_PROVEN_OOB":               "OOB! ",
}

VERDICT_COLOR = {
    "TP_PROVEN":                   "\033[91m",
    "TP_PROVEN_OOB":               "\033[91;1m",
    "PROBABLE_FP_VERIFIED":        "\033[92m",
    "INDETERMINATE_TEST_INVALID":  "\033[93m",
    "CACHED":                      "\033[96m",
    "NO_POC":                      "\033[90m",
    "SKIPPED":                     "\033[90m",
    "FIX_VERIFIED":                "\033[92m",
    "FIX_INCOMPLETE":              "\033[91;1m",
}
RESET = "\033[0m"


# ─────────────────────────────────────────────────────────────────────────────
# 2. Data model
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class PoCResult:
    finding: dict
    verdict: str
    duration_ms: int = 0
    exit_code: int = 0
    stdout: str = ""
    stderr: str = ""
    command: str = ""
    reason: str = ""
    poc_file: str = ""
    # Mode-specific extras:
    variants: list[dict] = field(default_factory=list)          # --variants
    auth_matrix: dict[str, str] = field(default_factory=dict)   # --auth-ladder: level → verdict
    oob_hit: bool = False                                       # --blind
    chains: list[dict] = field(default_factory=list)            # --chains
    post_exploit: dict | None = None                            # --post-exploit


# ─────────────────────────────────────────────────────────────────────────────
# 3. Paths & scan loading
# ─────────────────────────────────────────────────────────────────────────────

def resolve_paths(cwd: Path) -> dict[str, Path]:
    state = cwd / ".agentic-security"
    return {
        "scan":       state / "last-scan.json",
        "poc":        state / "poc",
        "cache":      state / "poc-cache",
        "history":    state / "validator-history.json",
        "auth":       state / "auth-fixtures.json",
        "post_tmpl":  SCRIPT_DIR / "validator" / "post_exploit_templates.json",
        "chain_rules": SCRIPT_DIR / "validator" / "chain_rules.json",
    }


def load_scan(scan_path: Path) -> list[dict]:
    if not scan_path.exists():
        print(f"ERROR: {scan_path} not found — run /scan --all first.", file=sys.stderr)
        sys.exit(1)
    data = json.loads(scan_path.read_text())
    findings = []
    for key in ("findings", "logicVulns", "supplyChain"):
        findings.extend(data.get(key, []))
    return findings


def sev_idx(sev: str) -> int:
    try:
        return SEVERITY_ORDER.index((sev or "info").lower())
    except ValueError:
        return len(SEVERITY_ORDER)


# ─────────────────────────────────────────────────────────────────────────────
# 4. Framework detection (reuses validator/detect-framework.mjs when present)
# ─────────────────────────────────────────────────────────────────────────────

def detect_framework(cwd: Path) -> dict:
    script = SCRIPT_DIR / "validator" / "detect-framework.mjs"
    if script.exists():
        result = subprocess.run(
            ["node", str(script), str(cwd)],
            capture_output=True, text=True, timeout=10, cwd=str(cwd),
        )
        if result.returncode == 0:
            try:
                return json.loads(result.stdout)
            except json.JSONDecodeError:
                pass

    # Fallback sniff
    pkg = cwd / "package.json"
    if pkg.exists():
        try:
            pkg_data = json.loads(pkg.read_text())
            deps = {**pkg_data.get("dependencies", {}), **pkg_data.get("devDependencies", {})}
            if "vitest" in deps:
                return {"framework": "vitest", "runner": "npx vitest run", "ext": "test.ts", "lang": "ts"}
            if "jest" in deps:
                return {"framework": "jest", "runner": "npx jest", "ext": "test.js", "lang": "js"}
            if "mocha" in deps:
                return {"framework": "mocha", "runner": "npx mocha", "ext": "test.js", "lang": "js"}
        except Exception:
            pass
        return {"framework": "node-test", "runner": "node --test", "ext": "test.js", "lang": "js"}
    if any((cwd / p).exists() for p in ("pyproject.toml", "setup.py", "pytest.ini")):
        return {"framework": "pytest", "runner": "pytest -v", "ext": "test.py", "lang": "python"}
    if (cwd / "go.mod").exists():
        return {"framework": "go-test", "runner": "go test", "ext": "test.go", "lang": "go"}
    if (cwd / "Cargo.toml").exists():
        return {"framework": "cargo-test", "runner": "cargo test", "ext": "rs", "lang": "rust"}
    return {"framework": "none", "runner": None, "ext": None, "lang": None}


def build_command(framework: str, test_file: Path, cwd: Path) -> list[str] | None:
    if framework == "go-test":
        return ["go", "test", "-run", ".", str(test_file.parent)]
    if framework == "cargo-test":
        manifest = test_file.parent
        while manifest != cwd and manifest != manifest.parent and not (manifest / "Cargo.toml").exists():
            manifest = manifest.parent
        if not (manifest / "Cargo.toml").exists():
            manifest = cwd
        return ["cargo", "test", "--manifest-path", str(manifest / "Cargo.toml")]
    if framework == "dotnet-test":
        return ["dotnet", "test", "--filter", f"FullyQualifiedName~{test_file.stem}"]
    if framework == "junit":
        return ["mvn", "test", f"-Dtest={test_file.stem}"]
    base = FRAMEWORK_RUNNERS.get(framework)
    if not base:
        return None
    return [*base, str(test_file)]


# ─────────────────────────────────────────────────────────────────────────────
# 5. Test execution primitive
# ─────────────────────────────────────────────────────────────────────────────

def run_test(test_file: Path, framework: str, timeout: int, cwd: Path,
             extra_env: dict[str, str] | None = None) -> dict:
    cmd = build_command(framework, test_file, cwd)
    if not cmd:
        return {"verdict": "INDETERMINATE_TEST_INVALID",
                "reason": f"no runner for framework: {framework}",
                "exit_code": -1, "duration_ms": 0, "stdout": "", "stderr": "", "command": ""}

    env = {**os.environ, **(extra_env or {})}
    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout, cwd=str(cwd), env=env,
        )
        duration_ms = int((time.monotonic() - t0) * 1000)
        verdict = "TP_PROVEN" if proc.returncode != 0 else "PROBABLE_FP_VERIFIED"
        return {
            "verdict": verdict, "exit_code": proc.returncode, "duration_ms": duration_ms,
            "stdout": proc.stdout[:6000], "stderr": proc.stderr[:3000], "command": " ".join(cmd),
        }
    except subprocess.TimeoutExpired:
        return {"verdict": "INDETERMINATE_TEST_INVALID", "reason": f"timed out after {timeout}s",
                "exit_code": -1, "duration_ms": int((time.monotonic() - t0) * 1000),
                "stdout": "", "stderr": "", "command": " ".join(cmd)}
    except FileNotFoundError as e:
        return {"verdict": "INDETERMINATE_TEST_INVALID", "reason": f"runner not found: {e}",
                "exit_code": -1, "duration_ms": 0, "stdout": "", "stderr": "", "command": " ".join(cmd)}


# ─────────────────────────────────────────────────────────────────────────────
# 6. PoC discovery
# ─────────────────────────────────────────────────────────────────────────────

def find_poc_file(poc_dir: Path, finding_id: str) -> Path | None:
    if not poc_dir.exists():
        return None
    safe = finding_id.replace("/", "_").replace(":", "_")
    direct = poc_dir / safe
    if direct.exists():
        cands = sorted(direct.glob("poc.*"))
        if cands:
            return cands[0]
    for d in poc_dir.iterdir():
        if d.is_dir() and (finding_id in d.name or d.name in finding_id):
            cands = sorted(d.glob("poc.*"))
            if cands:
                return cands[0]
    return None


def load_variants(poc_file: Path) -> list[dict]:
    """Load .agentic-security/poc/<id>/variants.json. Schema:
       [{"label": "unicode-quote", "payload": "ʼ OR ʼ1ʼ=ʼ1"}, ...]
    """
    variants_path = poc_file.parent / "variants.json"
    if not variants_path.exists():
        return []
    try:
        data = json.loads(variants_path.read_text())
        if isinstance(data, list):
            return [v for v in data if isinstance(v, dict) and "payload" in v]
    except Exception:
        pass
    return []


# ─────────────────────────────────────────────────────────────────────────────
# 7. Cache
# ─────────────────────────────────────────────────────────────────────────────

def cache_key(finding: dict, cwd: Path) -> str:
    file_path = finding.get("file") or finding.get("sink", {}).get("file", "")
    abs_file = (cwd / file_path).resolve() if file_path else Path("/dev/null")
    try:
        file_hash = hashlib.sha256(abs_file.read_bytes()).hexdigest()[:12]
    except Exception:
        file_hash = "nofile"
    try:
        version = json.loads((cwd / "package.json").read_text()).get("version", "unknown")
    except Exception:
        version = "unknown"
    raw = f"{finding['id']}::{file_hash}::{version}"
    return hashlib.sha256(raw.encode()).hexdigest()[:24]


def read_cache(cache_dir: Path, finding: dict, cwd: Path) -> dict | None:
    f = cache_dir / f"{cache_key(finding, cwd)}.json"
    if f.exists():
        try:
            return json.loads(f.read_text())
        except Exception:
            return None
    return None


def write_cache(cache_dir: Path, finding: dict, cwd: Path, verdict: dict) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    (cache_dir / f"{cache_key(finding, cwd)}.json").write_text(json.dumps(verdict, indent=2))


# ─────────────────────────────────────────────────────────────────────────────
# 8. CWE / family classification
# ─────────────────────────────────────────────────────────────────────────────

def cwe_of(finding: dict) -> str:
    return (finding.get("cwe") or "").upper().strip()


def cwe_matches(actual: str, pattern: str) -> bool:
    if not pattern:
        return False
    return actual in {p.strip().upper() for p in pattern.split("|") if p.strip()}


def vuln_family(finding: dict) -> str:
    """Best-effort family classification for routing to post-exploit templates."""
    cwe = cwe_of(finding)
    if cwe:
        return cwe
    vuln = (finding.get("vuln") or "").lower()
    if "sql" in vuln and "inj" in vuln:        return "CWE-89"
    if "command inj" in vuln or "rce" in vuln: return "CWE-78"
    if "path trav" in vuln or "lfi" in vuln:   return "CWE-22"
    if "ssrf" in vuln:                          return "CWE-918"
    if "xss" in vuln:                           return "CWE-79"
    if "idor" in vuln:                          return "CWE-639"
    if "prototype pollut" in vuln:              return "CWE-1321"
    if "open redirect" in vuln:                 return "CWE-601"
    if "mass assign" in vuln:                   return "CWE-915"
    if "prompt inj" in vuln:                    return "LLM01"
    if "deserial" in vuln:                      return "CWE-502"
    if "xxe" in vuln:                           return "CWE-611"
    return "DEFAULT"


# ─────────────────────────────────────────────────────────────────────────────
# 9. NEW: Adversarial variants
# ─────────────────────────────────────────────────────────────────────────────

def run_variants(poc_file: Path, framework: str, timeout: int, cwd: Path,
                 extra_env: dict[str, str] | None = None) -> list[dict]:
    """Run each variant in variants.json by injecting AS_POC_PAYLOAD env var.

    Test files generated by the agent should honor AS_POC_PAYLOAD when set:
      const payload = process.env.AS_POC_PAYLOAD || "<canonical>";

    Each variant becomes a separate run; we report which fire (TP) and which
    are blocked (PASSED). The set of firing variants tells you which
    encodings/bypasses get past the application's filters.
    """
    variants = load_variants(poc_file)
    if not variants:
        return []
    base_env = dict(extra_env or {})
    out = []
    for v in variants:
        label = v.get("label", "unnamed")
        payload = v["payload"]
        env = {**base_env, "AS_POC_PAYLOAD": payload, "AS_POC_VARIANT": label}
        r = run_test(poc_file, framework, timeout, cwd, extra_env=env)
        out.append({
            "label": label,
            "payload": payload,
            "verdict": r["verdict"],
            "duration_ms": r["duration_ms"],
        })
    return out


# ─────────────────────────────────────────────────────────────────────────────
# 10. NEW: Auth-context ladder
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_AUTH_FIXTURE = {
    "unauth": {"token": "", "user_id": ""},
    "low":    {"token": "AS_LOW_PRIV_TOKEN_REPLACE_ME", "user_id": "1"},
    "high":   {"token": "AS_HIGH_PRIV_TOKEN_REPLACE_ME", "user_id": "999"},
}


def load_auth_fixture(auth_path: Path) -> dict:
    if not auth_path.exists():
        return {}
    try:
        return json.loads(auth_path.read_text())
    except Exception:
        return {}


def run_auth_ladder(poc_file: Path, framework: str, timeout: int, cwd: Path,
                    fixture: dict) -> dict[str, str]:
    """Re-run the PoC at three auth levels. Test files should honor
       AS_POC_AUTH_LEVEL and AS_POC_AUTH_TOKEN env vars.
       Returns {level: verdict}.
    """
    if not fixture:
        return {}
    out: dict[str, str] = {}
    for level in ("unauth", "low", "high"):
        ctx = fixture.get(level, DEFAULT_AUTH_FIXTURE[level])
        env = {
            "AS_POC_AUTH_LEVEL": level,
            "AS_POC_AUTH_TOKEN": ctx.get("token", ""),
            "AS_POC_AUTH_USER_ID": str(ctx.get("user_id", "")),
        }
        r = run_test(poc_file, framework, timeout, cwd, extra_env=env)
        out[level] = r["verdict"]
    return out


# ─────────────────────────────────────────────────────────────────────────────
# 11. NEW: Blind / OOB callback listener
# ─────────────────────────────────────────────────────────────────────────────

class OOBListener:
    """Tiny HTTP listener for out-of-band callback detection (blind SQLi/SSRF/XSS).

    Spins up a ThreadingHTTPServer on a random localhost port. Each test gets
    a unique token; the test injects http://127.0.0.1:<port>/<token> into its
    payload. After the test runs we check if the token was hit.
    """

    def __init__(self):
        self.hits: dict[str, list[dict]] = {}
        self._server: http.server.HTTPServer | None = None
        self._thread: threading.Thread | None = None
        self._port: int = 0
        self._lock = threading.Lock()

    def start(self) -> None:
        hits = self.hits
        lock = self._lock

        class Handler(http.server.BaseHTTPRequestHandler):
            def _record(self):
                token = self.path.lstrip("/").split("?")[0].split("/")[0] or "_root"
                with lock:
                    hits.setdefault(token, []).append({
                        "method": self.command, "path": self.path,
                        "client": self.client_address[0],
                        "ts": time.time(),
                    })
                self.send_response(200)
                self.end_headers()
                self.wfile.write(b"ok")

            def do_GET(self):    self._record()
            def do_POST(self):   self._record()
            def do_HEAD(self):   self._record()
            def log_message(self, *_a, **_kw): pass

        sock = socket.socket()
        sock.bind(("127.0.0.1", 0))
        self._port = sock.getsockname()[1]
        sock.close()

        self._server = http.server.ThreadingHTTPServer(("127.0.0.1", self._port), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self._port}"

    def token_url(self, token: str) -> str:
        return f"{self.base_url}/{token}"

    def was_hit(self, token: str) -> bool:
        with self._lock:
            return token in self.hits and len(self.hits[token]) > 0

    def stop(self) -> None:
        if self._server:
            self._server.shutdown()
            self._server.server_close()


# ─────────────────────────────────────────────────────────────────────────────
# 12. NEW: Post-exploitation templates
# ─────────────────────────────────────────────────────────────────────────────

def load_post_exploit_templates(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def post_exploit_for(finding: dict, templates: dict) -> dict | None:
    if not templates:
        return None
    fam = vuln_family(finding)
    return templates.get(fam) or templates.get("DEFAULT")


# ─────────────────────────────────────────────────────────────────────────────
# 13. NEW: Attack chain correlation
# ─────────────────────────────────────────────────────────────────────────────

def load_chain_rules(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        return json.loads(path.read_text()).get("rules", [])
    except Exception:
        return []


def find_chains(primary: dict, all_findings: list[dict], rules: list[dict]) -> list[dict]:
    """For a TP_PROVEN finding, find other findings in the scan that combine
       with it under a known chain rule. Returns enriched chain descriptions.
    """
    out = []
    p_cwe = cwe_of(primary)
    if not p_cwe:
        p_cwe = vuln_family(primary)
    for rule in rules:
        if not cwe_matches(p_cwe, rule.get("primary_cwe", "")):
            continue
        for other in all_findings:
            if other.get("id") == primary.get("id"):
                continue
            o_cwe = cwe_of(other) or vuln_family(other)
            if not cwe_matches(o_cwe, rule.get("secondary_cwe", "")):
                continue
            if rule.get("same_file_required") and other.get("file") != primary.get("file"):
                continue
            narrative = rule.get("narrative", "")
            narrative = (narrative
                         .replace("{primary.file}", primary.get("file", "?"))
                         .replace("{primary.line}", str(primary.get("line", "?")))
                         .replace("{secondary.file}", other.get("file", "?"))
                         .replace("{secondary.line}", str(other.get("line", "?"))))
            out.append({
                "name": rule.get("name", "chain"),
                "secondary_id": other.get("id"),
                "chained_severity": rule.get("chained_severity", "high"),
                "narrative": narrative,
            })
    return out


# ─────────────────────────────────────────────────────────────────────────────
# 14. NEW: Fix verification
# ─────────────────────────────────────────────────────────────────────────────

def verify_fix(result: dict) -> str:
    """Invert the verdict semantics: when verifying a fix, we WANT the test
       to pass (assertion no longer fires). Returns FIX_VERIFIED or
       FIX_INCOMPLETE; INDETERMINATE passes through.
    """
    v = result["verdict"]
    if v == "INDETERMINATE_TEST_INVALID":
        return v
    if v == "PROBABLE_FP_VERIFIED":  # test passed = vuln blocked = fix worked
        return "FIX_VERIFIED"
    if v == "TP_PROVEN":             # test still fails = vuln still triggers
        return "FIX_INCOMPLETE"
    return v


# ─────────────────────────────────────────────────────────────────────────────
# 15. Reporting / output
# ─────────────────────────────────────────────────────────────────────────────

def colored(text: str, verdict: str, use_color: bool) -> str:
    if not use_color:
        return text
    return f"{VERDICT_COLOR.get(verdict, '')}{text}{RESET}"


def print_result_line(r: PoCResult, use_color: bool) -> None:
    icon = VERDICT_ICONS.get(r.verdict, r.verdict)
    sev = (r.finding.get("severity") or "?").lower()
    fid = r.finding.get("id", "?")
    label = colored(f"[{icon}]", r.verdict, use_color)
    suffix = ""
    if r.verdict == "CACHED":
        suffix = f"  (cached: {r.reason})"
    elif r.verdict == "NO_POC":
        suffix = "  (no PoC — run /validate-findings first)"
    elif r.duration_ms:
        suffix = f"  ({r.duration_ms}ms)"
    print(f"{label} {sev:<8} {fid[:55]:<55}{suffix}")


def print_variant_matrix(r: PoCResult, use_color: bool) -> None:
    if not r.variants:
        return
    print(f"       variants:")
    for v in r.variants:
        mark = "FIRES " if v["verdict"] == "TP_PROVEN" else \
               "blocked" if v["verdict"] == "PROBABLE_FP_VERIFIED" else "error"
        c = "TP_PROVEN" if v["verdict"] == "TP_PROVEN" else "PROBABLE_FP_VERIFIED"
        print(f"         {colored(mark, c, use_color):<22} {v['label']:<22} ({v['duration_ms']}ms)")


def print_auth_matrix(r: PoCResult, use_color: bool) -> None:
    if not r.auth_matrix:
        return
    print(f"       auth-ladder:")
    for level, verdict in r.auth_matrix.items():
        c = "TP_PROVEN" if verdict == "TP_PROVEN" else "PROBABLE_FP_VERIFIED"
        mark = "FIRES " if verdict == "TP_PROVEN" else "blocked"
        print(f"         {colored(mark, c, use_color):<14} {level}")


def print_chains(r: PoCResult, use_color: bool) -> None:
    if not r.chains:
        return
    print(f"       attack chains:")
    for ch in r.chains:
        label = colored(f"  ⛓ {ch['name']} → severity={ch['chained_severity']}", "TP_PROVEN", use_color)
        print(f"       {label}")
        for line in ch["narrative"].split(". "):
            line = line.strip()
            if line:
                print(f"         {line}{'.' if not line.endswith('.') else ''}")


def print_post_exploit(r: PoCResult, use_color: bool) -> None:
    pe = r.post_exploit
    if not pe:
        return
    print(f"       post-exploit ({pe.get('name', '?')}):")
    blast = pe.get("blast_radius", "")
    if blast:
        print(f"         blast radius: {blast}")
    for step in pe.get("next_steps", []):
        print(f"           ↳ {step}")


def emit_junit(results: list[PoCResult], path: Path) -> None:
    suite = ET.Element("testsuite", name="agentic-security-poc", tests=str(len(results)))
    for r in results:
        fid = r.finding.get("id", "?")
        tc = ET.SubElement(suite, "testcase", name=fid, classname=r.finding.get("vuln", "unknown"))
        tc.set("time", str(r.duration_ms / 1000))
        v = r.verdict
        if v in ("TP_PROVEN", "TP_PROVEN_OOB", "FIX_INCOMPLETE"):
            fail = ET.SubElement(tc, "failure", message=f"{v}: vulnerability confirmed")
            fail.text = (r.stdout or "")[:2000]
        elif v == "INDETERMINATE_TEST_INVALID":
            err = ET.SubElement(tc, "error", message=r.reason or "test errored")
            err.text = (r.stderr or "")[:2000]
        elif v == "NO_POC":
            ET.SubElement(tc, "skipped", message="No PoC test generated yet — run /validate-findings first")
    tree = ET.ElementTree(suite)
    ET.indent(tree, space="  ")
    tree.write(str(path), encoding="unicode", xml_declaration=True)
    print(f"\nJUnit XML → {path}")


def emit_evidence_bundle(results: list[PoCResult], cwd: Path, out_path: Path) -> None:
    """Pack TP_PROVEN findings + their PoCs + outputs into a single JSON
       evidence bundle suitable for a pentest report or client deliverable.
    """
    bundle = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "project": str(cwd),
        "findings": [],
    }
    for r in results:
        if r.verdict not in ("TP_PROVEN", "TP_PROVEN_OOB", "FIX_INCOMPLETE"):
            continue
        entry = {
            "id": r.finding.get("id"),
            "vuln": r.finding.get("vuln"),
            "cwe": r.finding.get("cwe"),
            "severity": r.finding.get("severity"),
            "file": r.finding.get("file"),
            "line": r.finding.get("line"),
            "verdict": r.verdict,
            "command": r.command,
            "duration_ms": r.duration_ms,
            "stdout_tail": (r.stdout or "")[-2000:],
            "stderr_tail": (r.stderr or "")[-2000:],
            "poc_file": r.poc_file,
            "variants": r.variants,
            "auth_matrix": r.auth_matrix,
            "oob_hit": r.oob_hit,
            "chains": r.chains,
            "post_exploit": r.post_exploit,
        }
        # Inline the test file content too, so the bundle is self-contained
        try:
            if r.poc_file and Path(r.poc_file).exists():
                entry["poc_test_source"] = Path(r.poc_file).read_text()[:20000]
        except Exception:
            pass
        bundle["findings"].append(entry)
    out_path.write_text(json.dumps(bundle, indent=2))
    print(f"\nEvidence bundle → {out_path}  ({len(bundle['findings'])} proven finding(s))")


# ─────────────────────────────────────────────────────────────────────────────
# 16. Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Batch-execute PoC tests generated by /agentic-security:validate-findings",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Filters
    parser.add_argument("--severity", choices=SEVERITY_ORDER, default=None,
                        help="minimum severity to include (default: all)")
    parser.add_argument("--id", dest="finding_id", default=None,
                        help="run a single finding by ID")
    # Modes
    parser.add_argument("--list", action="store_true",
                        help="list available PoCs without running")
    parser.add_argument("--variants", action="store_true",
                        help="run all adversarial variants per finding (WAF/filter bypass surface)")
    parser.add_argument("--auth-ladder", action="store_true",
                        help="run each PoC under unauth/low-priv/high-priv contexts")
    parser.add_argument("--verify-fix", action="store_true",
                        help="confirm previously-proven findings no longer fire after /fix")
    parser.add_argument("--chains", action="store_true",
                        help="correlate TP_PROVEN findings into multi-step attack chains")
    parser.add_argument("--blind", action="store_true",
                        help="enable OOB callback listener for blind SQLi/SSRF/XSS")
    parser.add_argument("--post-exploit", action="store_true",
                        help="show post-exploitation suggestions for each TP_PROVEN finding")
    # Output
    parser.add_argument("--json", action="store_true", help="output results as JSON")
    parser.add_argument("--junit", default=None, help="write JUnit XML to this path")
    parser.add_argument("--evidence", default=None,
                        help="write self-contained evidence bundle (JSON) to this path")
    # Runtime
    parser.add_argument("--timeout", type=int, default=60,
                        help="per-test timeout in seconds (default: 60)")
    parser.add_argument("--no-cache", action="store_true", help="ignore cached verdicts")
    parser.add_argument("--cwd", default=None, help="project root (default: current directory)")
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve() if args.cwd else Path.cwd()
    use_color = sys.stdout.isatty() and not args.json
    paths = resolve_paths(cwd)
    findings = load_scan(paths["scan"])
    fw = detect_framework(cwd)
    auth_fixture = load_auth_fixture(paths["auth"])
    post_templates = load_post_exploit_templates(paths["post_tmpl"])
    chain_rules = load_chain_rules(paths["chain_rules"])

    # Filter
    min_sev = sev_idx(args.severity) if args.severity else len(SEVERITY_ORDER)
    targets = []
    for f in findings:
        if args.finding_id and f.get("id") != args.finding_id:
            continue
        if sev_idx(f.get("severity", "info")) > min_sev:
            continue
        targets.append(f)
    if not targets:
        print("No findings match the given filters.")
        sys.exit(0)

    if args.list:
        print(f"{'ID':<60}  {'SEV':<8}  {'POC?':<5}  {'VARIANTS':<8}")
        print("-" * 90)
        for f in targets:
            poc = find_poc_file(paths["poc"], f["id"])
            has = "yes" if poc else "no"
            vcount = len(load_variants(poc)) if poc else 0
            print(f"{f['id'][:60]:<60}  {f.get('severity','?'):<8}  {has:<5}  {vcount:<8}")
        sys.exit(0)

    # Banner
    print(f"Framework:      {fw.get('framework','none')}  ({fw.get('runner') or 'n/a'})")
    if args.auth_ladder:
        print(f"Auth fixture:   {paths['auth']}  ({'loaded' if auth_fixture else 'MISSING — using defaults'})")
    oob: OOBListener | None = None
    if args.blind:
        oob = OOBListener()
        oob.start()
        print(f"OOB listener:   {oob.base_url}  (token-based blind-vuln detection)")
    if args.verify_fix:
        print("Mode:           --verify-fix (inverted verdicts: PASS = fix worked)")
    print(f"\nRunning PoCs for {len(targets)} finding(s)...\n")

    results: list[PoCResult] = []

    for f in targets:
        fid = f["id"]
        r = PoCResult(finding=f, verdict="SKIPPED")

        # Cache
        if not args.no_cache and not args.verify_fix:
            cached = read_cache(paths["cache"], f, cwd)
            if cached:
                r.verdict = "CACHED"
                r.reason = cached.get("verdict", "?")
                results.append(r)
                print_result_line(r, use_color)
                continue

        # Locate PoC
        poc_file = find_poc_file(paths["poc"], fid)
        if not poc_file:
            r.verdict = "NO_POC"
            results.append(r)
            print_result_line(r, use_color)
            continue
        r.poc_file = str(poc_file)

        # Inject OOB callback URL if blind mode active
        extra_env: dict[str, str] = {}
        oob_token = ""
        if oob:
            oob_token = uuid.uuid4().hex[:16]
            extra_env["AS_POC_OOB_URL"] = oob.token_url(oob_token)
            extra_env["AS_POC_OOB_TOKEN"] = oob_token

        # Run canonical
        run_result = run_test(poc_file, fw.get("framework", "none"), args.timeout, cwd,
                              extra_env=extra_env or None)
        r.verdict = run_result["verdict"]
        r.duration_ms = run_result["duration_ms"]
        r.exit_code = run_result.get("exit_code", -1)
        r.stdout = run_result.get("stdout", "")
        r.stderr = run_result.get("stderr", "")
        r.command = run_result.get("command", "")
        r.reason = run_result.get("reason", "")

        # OOB upgrade
        if oob and oob_token and oob.was_hit(oob_token):
            r.oob_hit = True
            if r.verdict in ("PROBABLE_FP_VERIFIED", "INDETERMINATE_TEST_INVALID"):
                # Test passed/errored, but the listener got a hit → blind vuln confirmed
                r.verdict = "TP_PROVEN_OOB"
            elif r.verdict == "TP_PROVEN":
                r.verdict = "TP_PROVEN_OOB"

        # --verify-fix: invert
        if args.verify_fix:
            r.verdict = verify_fix({"verdict": r.verdict})

        # --variants
        if args.variants and r.verdict in ("TP_PROVEN", "TP_PROVEN_OOB"):
            r.variants = run_variants(poc_file, fw.get("framework", "none"), args.timeout, cwd,
                                      extra_env=extra_env)

        # --auth-ladder
        if args.auth_ladder:
            fixture = auth_fixture or DEFAULT_AUTH_FIXTURE
            r.auth_matrix = run_auth_ladder(poc_file, fw.get("framework", "none"),
                                            args.timeout, cwd, fixture)

        # --chains
        if args.chains and r.verdict in ("TP_PROVEN", "TP_PROVEN_OOB", "FIX_INCOMPLETE"):
            r.chains = find_chains(f, findings, chain_rules)

        # --post-exploit
        if args.post_exploit and r.verdict in ("TP_PROVEN", "TP_PROVEN_OOB", "FIX_INCOMPLETE"):
            r.post_exploit = post_exploit_for(f, post_templates)

        # Cache canonical verdict (not in fix-verify mode, that's a separate axis)
        if not args.no_cache and not args.verify_fix and \
           r.verdict in ("TP_PROVEN", "PROBABLE_FP_VERIFIED", "TP_PROVEN_OOB"):
            write_cache(paths["cache"], f, cwd, {
                "verdict": r.verdict, "duration_ms": r.duration_ms, "oob_hit": r.oob_hit,
            })

        results.append(r)
        print_result_line(r, use_color)
        if args.variants:    print_variant_matrix(r, use_color)
        if args.auth_ladder: print_auth_matrix(r, use_color)
        if args.chains:      print_chains(r, use_color)
        if args.post_exploit:print_post_exploit(r, use_color)
        if r.verdict in ("TP_PROVEN", "TP_PROVEN_OOB", "FIX_INCOMPLETE", "INDETERMINATE_TEST_INVALID") and not args.json:
            tail = (r.stdout + r.stderr).strip().splitlines()[:12]
            if tail:
                print("       " + "\n       ".join(tail))
            print()

    if oob:
        oob.stop()

    # Summary
    counts: dict[str, int] = {}
    for r in results:
        counts[r.verdict] = counts.get(r.verdict, 0) + 1

    if not args.json:
        print("\n" + "─" * 60)
        print(f"Summary  ({len(results)} findings):")
        for v in sorted(counts):
            label = colored(f"  [{VERDICT_ICONS.get(v, v)}]", v, use_color)
            print(f"{label}  {v:<30} {counts[v]}")
        proven = counts.get("TP_PROVEN", 0) + counts.get("TP_PROVEN_OOB", 0)
        broke  = counts.get("FIX_INCOMPLETE", 0)
        if proven:
            print(f"\n  {proven} TP_PROVEN finding(s) — run /agentic-security:fix --all --high to remediate")
        if broke:
            print(f"\n  {broke} FIX_INCOMPLETE finding(s) — the fix did NOT block the original PoC")

    if args.json:
        print(json.dumps([asdict(r) for r in results], indent=2, default=str))

    if args.junit:
        emit_junit(results, Path(args.junit))
    if args.evidence:
        emit_evidence_bundle(results, cwd, Path(args.evidence))

    # Exit 1 if any proven (or incomplete fix) → CI gate
    bad = counts.get("TP_PROVEN", 0) + counts.get("TP_PROVEN_OOB", 0) + counts.get("FIX_INCOMPLETE", 0)
    sys.exit(1 if bad > 0 else 0)


if __name__ == "__main__":
    main()
