#!/usr/bin/env python3
"""
run-poc-tests.py — batch-execute PoC test files generated by /agentic-security:validate-findings

Usage:
  python3 scripts/run-poc-tests.py [options]

Options:
  --severity LEVEL    Only run PoCs for findings at or above: critical, high, medium, low (default: all)
  --id FINDING_ID     Run a single finding's PoC by ID
  --list              List available PoCs without running them
  --json              Output results as JSON (for CI ingestion)
  --timeout SEC       Per-test timeout in seconds (default: 60)
  --no-cache          Ignore cached verdicts; re-run even if a cached result exists
  --junit PATH        Write JUnit XML to PATH

Verdicts emitted:
  TP_PROVEN            Test ran and FAILED  → bug is real (assertion on vuln behaviour fired)
  PROBABLE_FP_VERIFIED Test ran and PASSED  → data flow is blocked (likely false positive)
  INDETERMINATE_TEST_INVALID  Test errored (compile/import/timeout)
  CACHED               Returned from verdict cache (no test executed)
  NO_POC               Finding has no generated PoC test yet (run /validate-findings first)
  SKIPPED              Filtered out by --severity or --id
"""

import argparse
import json
import os
import subprocess
import sys
import time
import hashlib
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime, timezone

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

FRAMEWORK_RUNNERS = {
    "jest":        ["npx", "jest", "--"],
    "vitest":      ["npx", "vitest", "run"],
    "mocha":       ["npx", "mocha"],
    "node-test":   [sys.executable.replace("python3", "node") or "node", "--test"],
    "pytest":      ["pytest", "-v"],
    "go-test":     None,  # special-cased below
    "cargo-test":  None,  # special-cased below
    "dotnet-test": ["dotnet", "test", "--filter"],
    "junit":       ["mvn", "test"],
    "rspec":       ["bundle", "exec", "rspec"],
    "phpunit":     ["./vendor/bin/phpunit"],
}


def resolve_paths(cwd: Path) -> tuple[Path, Path, Path, Path]:
    state_dir = cwd / ".agentic-security"
    return (
        state_dir / "last-scan.json",
        state_dir / "poc",
        state_dir / "poc-cache",
        state_dir / "validator-history.json",
    )


def load_scan(scan_path: Path) -> list[dict]:
    if not scan_path.exists():
        print(f"ERROR: {scan_path} not found — run /scan --all first.", file=sys.stderr)
        sys.exit(1)
    with scan_path.open() as f:
        data = json.load(f)
    findings = []
    for key in ("findings", "logicVulns", "supplyChain"):
        findings.extend(data.get(key, []))
    return findings


def severity_index(sev: str) -> int:
    try:
        return SEVERITY_ORDER.index(sev.lower())
    except ValueError:
        return len(SEVERITY_ORDER)


def find_poc_file(poc_dir: Path, finding_id: str) -> Path | None:
    safe_id = finding_id.replace("/", "_").replace(":", "_")
    candidates = list((poc_dir / safe_id).glob("poc.*")) if (poc_dir / safe_id).exists() else []
    if not candidates:
        # also try raw id as directory name fragment
        for d in poc_dir.iterdir() if poc_dir.exists() else []:
            if d.is_dir() and finding_id in d.name:
                candidates = list(d.glob("poc.*"))
                break
    return candidates[0] if candidates else None


def detect_framework(cwd: Path) -> dict:
    detector = cwd / "node_modules" / ".bin" / "node"  # fallback
    # Try the validator script first
    script = Path(__file__).parent / "validator" / "detect-framework.mjs"
    if script.exists():
        result = subprocess.run(
            ["node", str(script), str(cwd)],
            capture_output=True, text=True, timeout=10, cwd=str(cwd),
        )
        if result.returncode == 0:
            try:
                return json.loads(result.stdout)
            except json.JSONDecodeError:
                pass

    # Fallback: sniff package.json / pyproject.toml / go.mod
    pkg = cwd / "package.json"
    if pkg.exists():
        try:
            deps = json.loads(pkg.read_text())
            all_deps = {**deps.get("dependencies", {}), **deps.get("devDependencies", {})}
            if "vitest" in all_deps:
                return {"framework": "vitest", "runner": "npx vitest run", "ext": "test.ts", "lang": "ts"}
            if "jest" in all_deps:
                return {"framework": "jest", "runner": "npx jest", "ext": "test.js", "lang": "js"}
            if "mocha" in all_deps:
                return {"framework": "mocha", "runner": "npx mocha", "ext": "test.js", "lang": "js"}
        except Exception:
            pass
        return {"framework": "node-test", "runner": "node --test", "ext": "test.js", "lang": "js"}
    if (cwd / "pyproject.toml").exists() or (cwd / "setup.py").exists() or (cwd / "pytest.ini").exists():
        return {"framework": "pytest", "runner": "pytest -v", "ext": "test.py", "lang": "python"}
    if (cwd / "go.mod").exists():
        return {"framework": "go-test", "runner": "go test", "ext": "test.go", "lang": "go"}
    if (cwd / "Cargo.toml").exists():
        return {"framework": "cargo-test", "runner": "cargo test", "ext": "rs", "lang": "rust"}
    return {"framework": "none", "runner": None, "ext": None, "lang": None}


def build_command(framework: str, test_file: Path, cwd: Path) -> list[str] | None:
    if framework == "go-test":
        return ["go", "test", "-run", ".", str(test_file.parent)]
    if framework == "cargo-test":
        manifest = test_file
        while manifest != cwd and not (manifest / "Cargo.toml").exists():
            manifest = manifest.parent
        return ["cargo", "test", "--manifest-path", str(manifest / "Cargo.toml")]
    if framework == "dotnet-test":
        return ["dotnet", "test", "--filter", f"FullyQualifiedName~{test_file.stem}"]
    if framework == "junit":
        return ["mvn", "test", f"-Dtest={test_file.stem}"]
    base = FRAMEWORK_RUNNERS.get(framework)
    if not base:
        return None
    return [*base, str(test_file)]


def run_poc(test_file: Path, framework: str, timeout: int, cwd: Path) -> dict:
    cmd = build_command(framework, test_file, cwd)
    if not cmd:
        return {
            "verdict": "INDETERMINATE_TEST_INVALID",
            "reason": f"no runner configured for framework: {framework}",
            "exitCode": -1, "durationMs": 0, "stdout": "", "stderr": "",
        }

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True, text=True,
            timeout=timeout,
            cwd=str(cwd),
        )
        duration_ms = int((time.monotonic() - t0) * 1000)
        exit_code = proc.returncode
        # PoC tests ASSERT vuln behaviour. Non-zero exit = test failed = bug proven.
        # Exit 0 = assertion didn't fire = probable FP.
        verdict = (
            "TP_PROVEN" if exit_code != 0
            else "PROBABLE_FP_VERIFIED"
        )
        return {
            "verdict": verdict,
            "exitCode": exit_code,
            "durationMs": duration_ms,
            "stdout": proc.stdout[:6000],
            "stderr": proc.stderr[:3000],
            "command": " ".join(cmd),
        }
    except subprocess.TimeoutExpired:
        duration_ms = int((time.monotonic() - t0) * 1000)
        return {
            "verdict": "INDETERMINATE_TEST_INVALID",
            "reason": f"timed out after {timeout}s",
            "exitCode": -1, "durationMs": duration_ms, "stdout": "", "stderr": "",
            "command": " ".join(cmd),
        }
    except FileNotFoundError as e:
        return {
            "verdict": "INDETERMINATE_TEST_INVALID",
            "reason": f"runner not found: {e}",
            "exitCode": -1, "durationMs": 0, "stdout": "", "stderr": "",
            "command": " ".join(cmd),
        }


def cache_key_for(finding: dict, cwd: Path) -> str:
    file_path = finding.get("file") or finding.get("sink", {}).get("file", "")
    abs_file = (cwd / file_path).resolve() if file_path else Path("/dev/null")
    try:
        file_hash = hashlib.sha256(abs_file.read_bytes()).hexdigest()[:12]
    except Exception:
        file_hash = "nofile"
    try:
        version = json.loads((cwd / "package.json").read_text()).get("version", "unknown")
    except Exception:
        version = "unknown"
    key_str = f"{finding['id']}::{file_hash}::{version}"
    return hashlib.sha256(key_str.encode()).hexdigest()[:24]


def read_cache(cache_dir: Path, finding: dict, cwd: Path) -> dict | None:
    key = cache_key_for(finding, cwd)
    cache_file = cache_dir / f"{key}.json"
    if cache_file.exists():
        try:
            return json.loads(cache_file.read_text())
        except Exception:
            pass
    return None


def write_cache(cache_dir: Path, finding: dict, cwd: Path, verdict: dict) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    key = cache_key_for(finding, cwd)
    (cache_dir / f"{key}.json").write_text(json.dumps(verdict, indent=2))


VERDICT_ICONS = {
    "TP_PROVEN":                   "FAIL",
    "PROBABLE_FP_VERIFIED":        "PASS",
    "INDETERMINATE_TEST_INVALID":  "ERR ",
    "CACHED":                      "CACHE",
    "NO_POC":                      "----",
    "SKIPPED":                     "SKIP",
}

VERDICT_COLOR = {
    "TP_PROVEN":                   "\033[91m",  # red
    "PROBABLE_FP_VERIFIED":        "\033[92m",  # green
    "INDETERMINATE_TEST_INVALID":  "\033[93m",  # yellow
    "CACHED":                      "\033[96m",  # cyan
    "NO_POC":                      "\033[90m",  # grey
    "SKIPPED":                     "\033[90m",
}
RESET = "\033[0m"


def colored(text: str, verdict: str, use_color: bool) -> str:
    if not use_color:
        return text
    return f"{VERDICT_COLOR.get(verdict, '')}{text}{RESET}"


def emit_junit(results: list[dict], path: Path) -> None:
    suite = ET.Element("testsuite", name="agentic-security-poc", tests=str(len(results)))
    for r in results:
        fid = r["finding"]["id"]
        tc = ET.SubElement(suite, "testcase", name=fid, classname=r["finding"].get("vuln", "unknown"))
        tc.set("time", str(r.get("durationMs", 0) / 1000))
        v = r["verdict"]
        if v == "TP_PROVEN":
            fail = ET.SubElement(tc, "failure", message="PoC test failed as expected — vulnerability confirmed")
            fail.text = r.get("stdout", "")[:2000]
        elif v == "INDETERMINATE_TEST_INVALID":
            err = ET.SubElement(tc, "error", message=r.get("reason", "test errored"))
            err.text = r.get("stderr", "")[:2000]
        elif v == "NO_POC":
            ET.SubElement(tc, "skipped", message="No PoC test generated yet — run /validate-findings first")
    tree = ET.ElementTree(suite)
    ET.indent(tree, space="  ")
    tree.write(str(path), encoding="unicode", xml_declaration=True)
    print(f"\nJUnit XML → {path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Batch-execute PoC tests generated by /agentic-security:validate-findings",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--severity", choices=SEVERITY_ORDER, default=None,
                        help="minimum severity to include (default: all)")
    parser.add_argument("--id", dest="finding_id", default=None,
                        help="run a single finding by ID")
    parser.add_argument("--list", action="store_true",
                        help="list available PoCs without running")
    parser.add_argument("--json", action="store_true",
                        help="output results as JSON")
    parser.add_argument("--timeout", type=int, default=60,
                        help="per-test timeout in seconds (default: 60)")
    parser.add_argument("--no-cache", action="store_true",
                        help="ignore cached verdicts")
    parser.add_argument("--junit", default=None,
                        help="write JUnit XML to this path")
    parser.add_argument("--cwd", default=None,
                        help="project root (default: current directory)")
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve() if args.cwd else Path.cwd()
    use_color = sys.stdout.isatty() and not args.json

    scan_path, poc_dir, cache_dir, history_path = resolve_paths(cwd)
    findings = load_scan(scan_path)

    fw = detect_framework(cwd)

    # --- filter ---
    min_sev_idx = severity_index(args.severity) if args.severity else len(SEVERITY_ORDER)

    targets = []
    for f in findings:
        if args.finding_id and f["id"] != args.finding_id:
            continue
        if severity_index(f.get("severity", "info")) > min_sev_idx:
            continue
        targets.append(f)

    if not targets:
        print("No findings match the given filters.")
        sys.exit(0)

    if args.list:
        print(f"{'ID':<60}  {'SEV':<8}  {'POC?'}")
        print("-" * 80)
        for f in targets:
            poc = find_poc_file(poc_dir, f["id"])
            has = "yes" if poc else "no"
            print(f"{f['id'][:60]:<60}  {f.get('severity','?'):<8}  {has}")
        sys.exit(0)

    print(f"Framework detected: {fw.get('framework','none')}   "
          f"Runner: {fw.get('runner') or 'n/a'}\n")
    print(f"Running PoCs for {len(targets)} finding(s)...\n")

    results = []
    for f in targets:
        fid = f["id"]
        vuln = f.get("vuln", fid)
        sev = f.get("severity", "?")

        # Check cache unless --no-cache
        if not args.no_cache:
            cached = read_cache(cache_dir, f, cwd)
            if cached:
                result = {
                    "finding": f,
                    "verdict": "CACHED",
                    "cached_verdict": cached.get("verdict"),
                    "durationMs": 0,
                }
                results.append(result)
                icon = VERDICT_ICONS["CACHED"]
                label = colored(f"[{icon}]", "CACHED", use_color)
                cv = cached.get("verdict", "?")
                print(f"{label} {sev:<8} {fid[:55]}  (cached: {cv})")
                continue

        # Find PoC test file
        poc_file = find_poc_file(poc_dir, fid)
        if not poc_file:
            result = {"finding": f, "verdict": "NO_POC", "durationMs": 0}
            results.append(result)
            icon = VERDICT_ICONS["NO_POC"]
            label = colored(f"[{icon}]", "NO_POC", use_color)
            print(f"{label} {sev:<8} {fid[:55]}  (no PoC — run /validate-findings first)")
            continue

        # Run the test
        run_result = run_poc(poc_file, fw.get("framework", "none"), args.timeout, cwd)
        verdict = run_result["verdict"]
        duration = run_result.get("durationMs", 0)

        result = {"finding": f, "poc_file": str(poc_file), **run_result}
        results.append(result)

        # Cache the new verdict
        if not args.no_cache and verdict in ("TP_PROVEN", "PROBABLE_FP_VERIFIED"):
            write_cache(cache_dir, f, cwd, run_result)

        icon = VERDICT_ICONS.get(verdict, "????")
        label = colored(f"[{icon}]", verdict, use_color)
        print(f"{label} {sev:<8} {fid[:55]}  ({duration}ms)")

        # Show truncated output on failure/error
        if verdict in ("TP_PROVEN", "INDETERMINATE_TEST_INVALID") and not args.json:
            out = run_result.get("stdout", "") + run_result.get("stderr", "")
            lines = out.strip().splitlines()[:20]
            if lines:
                print("       " + "\n       ".join(lines))
            print()

    # --- summary ---
    counts = {}
    for r in results:
        counts[r["verdict"]] = counts.get(r["verdict"], 0) + 1

    if not args.json:
        print("\n" + "─" * 60)
        print(f"Summary  ({len(results)} findings):")
        for v, n in sorted(counts.items()):
            icon = VERDICT_ICONS.get(v, v)
            label = colored(f"  [{icon}]", v, use_color)
            print(f"{label}  {v:<30} {n}")

        proven = counts.get("TP_PROVEN", 0)
        if proven:
            print(f"\n  {proven} TP_PROVEN finding(s) — run /agentic-security:fix --all --high to remediate")

    if args.json:
        print(json.dumps(results, indent=2, default=str))

    if args.junit:
        emit_junit(results, Path(args.junit))

    # Exit non-zero if any TP_PROVEN findings
    sys.exit(1 if counts.get("TP_PROVEN", 0) > 0 else 0)


if __name__ == "__main__":
    main()
